/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockesp_adc_mock_headers.h"

static const char* CMockString_adc_cali_create_scheme_curve_fitting = "adc_cali_create_scheme_curve_fitting";
static const char* CMockString_adc_cali_delete_scheme_curve_fitting = "adc_cali_delete_scheme_curve_fitting";
static const char* CMockString_adc_cali_raw_to_voltage = "adc_cali_raw_to_voltage";
static const char* CMockString_adc_oneshot_config_channel = "adc_oneshot_config_channel";
static const char* CMockString_adc_oneshot_del_unit = "adc_oneshot_del_unit";
static const char* CMockString_adc_oneshot_new_unit = "adc_oneshot_new_unit";
static const char* CMockString_adc_oneshot_read = "adc_oneshot_read";
static const char* CMockString_adc_raw = "adc_raw";
static const char* CMockString_channel = "channel";
static const char* CMockString_code = "code";
static const char* CMockString_config = "config";
static const char* CMockString_esp_err_to_name = "esp_err_to_name";
static const char* CMockString_handle = "handle";
static const char* CMockString_init_config = "init_config";
static const char* CMockString_out_raw = "out_raw";
static const char* CMockString_ret_handle = "ret_handle";
static const char* CMockString_ret_unit = "ret_unit";
static const char* CMockString_voltage_mv = "voltage_mv";

typedef struct _CMOCK_adc_oneshot_new_unit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  const adc_oneshot_unit_init_cfg_t* Expected_init_config;
  adc_oneshot_unit_handle_t* Expected_ret_unit;

} CMOCK_adc_oneshot_new_unit_CALL_INSTANCE;

typedef struct _CMOCK_adc_oneshot_config_channel_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  adc_oneshot_unit_handle_t Expected_handle;
  adc_channel_t Expected_channel;
  const adc_oneshot_chan_cfg_t* Expected_config;

} CMOCK_adc_oneshot_config_channel_CALL_INSTANCE;

typedef struct _CMOCK_adc_oneshot_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  adc_oneshot_unit_handle_t Expected_handle;
  adc_channel_t Expected_channel;
  int* Expected_out_raw;

} CMOCK_adc_oneshot_read_CALL_INSTANCE;

typedef struct _CMOCK_adc_oneshot_del_unit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  adc_oneshot_unit_handle_t Expected_handle;

} CMOCK_adc_oneshot_del_unit_CALL_INSTANCE;

typedef struct _CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  const adc_cali_curve_fitting_config_t* Expected_config;
  adc_cali_handle_t* Expected_ret_handle;

} CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE;

typedef struct _CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  adc_cali_handle_t Expected_handle;
  int Expected_adc_raw;
  int* Expected_voltage_mv;

} CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE;

typedef struct _CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  adc_cali_handle_t Expected_handle;

} CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE;

typedef struct _CMOCK_esp_err_to_name_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* ReturnVal;
  esp_err_t Expected_code;

} CMOCK_esp_err_to_name_CALL_INSTANCE;

static struct Mockesp_adc_mock_headersInstance
{
  CMOCK_MEM_INDEX_TYPE adc_oneshot_new_unit_CallInstance;
  CMOCK_MEM_INDEX_TYPE adc_oneshot_config_channel_CallInstance;
  CMOCK_MEM_INDEX_TYPE adc_oneshot_read_CallInstance;
  CMOCK_MEM_INDEX_TYPE adc_oneshot_del_unit_CallInstance;
  CMOCK_MEM_INDEX_TYPE adc_cali_create_scheme_curve_fitting_CallInstance;
  CMOCK_MEM_INDEX_TYPE adc_cali_raw_to_voltage_CallInstance;
  CMOCK_MEM_INDEX_TYPE adc_cali_delete_scheme_curve_fitting_CallInstance;
  CMOCK_MEM_INDEX_TYPE esp_err_to_name_CallInstance;
} Mock;


void Mockesp_adc_mock_headers_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.adc_oneshot_new_unit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_adc_oneshot_new_unit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.adc_oneshot_config_channel_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_adc_oneshot_config_channel);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.adc_oneshot_read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_adc_oneshot_read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.adc_oneshot_del_unit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_adc_oneshot_del_unit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.adc_cali_create_scheme_curve_fitting_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_adc_cali_create_scheme_curve_fitting);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.adc_cali_raw_to_voltage_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_adc_cali_raw_to_voltage);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.adc_cali_delete_scheme_curve_fitting_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_adc_cali_delete_scheme_curve_fitting);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.esp_err_to_name_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_err_to_name);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockesp_adc_mock_headers_Init(void)
{
  Mockesp_adc_mock_headers_Destroy();
}

void Mockesp_adc_mock_headers_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_err_t adc_oneshot_new_unit(const adc_oneshot_unit_init_cfg_t* init_config, adc_oneshot_unit_handle_t* ret_unit)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_adc_oneshot_new_unit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_adc_oneshot_new_unit);
  cmock_call_instance = (CMOCK_adc_oneshot_new_unit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.adc_oneshot_new_unit_CallInstance);
  Mock.adc_oneshot_new_unit_CallInstance = CMock_Guts_MemNext(Mock.adc_oneshot_new_unit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_new_unit,CMockString_init_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_init_config, init_config, sizeof(const adc_oneshot_unit_init_cfg_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_new_unit,CMockString_ret_unit);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_ret_unit, ret_unit, sizeof(adc_oneshot_unit_handle_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_adc_oneshot_new_unit(CMOCK_adc_oneshot_new_unit_CALL_INSTANCE* cmock_call_instance, const adc_oneshot_unit_init_cfg_t* init_config, adc_oneshot_unit_handle_t* ret_unit);
void CMockExpectParameters_adc_oneshot_new_unit(CMOCK_adc_oneshot_new_unit_CALL_INSTANCE* cmock_call_instance, const adc_oneshot_unit_init_cfg_t* init_config, adc_oneshot_unit_handle_t* ret_unit)
{
  cmock_call_instance->Expected_init_config = init_config;
  cmock_call_instance->Expected_ret_unit = ret_unit;
}

void adc_oneshot_new_unit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const adc_oneshot_unit_init_cfg_t* init_config, adc_oneshot_unit_handle_t* ret_unit, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_oneshot_new_unit_CALL_INSTANCE));
  CMOCK_adc_oneshot_new_unit_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_oneshot_new_unit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_oneshot_new_unit_CallInstance = CMock_Guts_MemChain(Mock.adc_oneshot_new_unit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_adc_oneshot_new_unit(cmock_call_instance, init_config, ret_unit);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

esp_err_t adc_oneshot_config_channel(adc_oneshot_unit_handle_t handle, adc_channel_t channel, const adc_oneshot_chan_cfg_t* config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_adc_oneshot_config_channel_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_adc_oneshot_config_channel);
  cmock_call_instance = (CMOCK_adc_oneshot_config_channel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.adc_oneshot_config_channel_CallInstance);
  Mock.adc_oneshot_config_channel_CallInstance = CMock_Guts_MemNext(Mock.adc_oneshot_config_channel_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_config_channel,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_handle, &handle, sizeof(adc_oneshot_unit_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_config_channel,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_channel, &channel, sizeof(adc_channel_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_config_channel,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_config, config, sizeof(const adc_oneshot_chan_cfg_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_adc_oneshot_config_channel(CMOCK_adc_oneshot_config_channel_CALL_INSTANCE* cmock_call_instance, adc_oneshot_unit_handle_t handle, adc_channel_t channel, const adc_oneshot_chan_cfg_t* config);
void CMockExpectParameters_adc_oneshot_config_channel(CMOCK_adc_oneshot_config_channel_CALL_INSTANCE* cmock_call_instance, adc_oneshot_unit_handle_t handle, adc_channel_t channel, const adc_oneshot_chan_cfg_t* config)
{
  memcpy((void*)(&cmock_call_instance->Expected_handle), (const void*)(&handle),
         sizeof(adc_oneshot_unit_handle_t[sizeof(handle) == sizeof(adc_oneshot_unit_handle_t) ? 1 : -1])); /* add adc_oneshot_unit_handle_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_channel), (const void*)(&channel),
         sizeof(adc_channel_t[sizeof(channel) == sizeof(adc_channel_t) ? 1 : -1])); /* add adc_channel_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_config = config;
}

void adc_oneshot_config_channel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_oneshot_unit_handle_t handle, adc_channel_t channel, const adc_oneshot_chan_cfg_t* config, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_oneshot_config_channel_CALL_INSTANCE));
  CMOCK_adc_oneshot_config_channel_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_oneshot_config_channel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_oneshot_config_channel_CallInstance = CMock_Guts_MemChain(Mock.adc_oneshot_config_channel_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_adc_oneshot_config_channel(cmock_call_instance, handle, channel, config);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

esp_err_t adc_oneshot_read(adc_oneshot_unit_handle_t handle, adc_channel_t channel, int* out_raw)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_adc_oneshot_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_adc_oneshot_read);
  cmock_call_instance = (CMOCK_adc_oneshot_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.adc_oneshot_read_CallInstance);
  Mock.adc_oneshot_read_CallInstance = CMock_Guts_MemNext(Mock.adc_oneshot_read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_read,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_handle, &handle, sizeof(adc_oneshot_unit_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_read,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_channel, &channel, sizeof(adc_channel_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_read,CMockString_out_raw);
    if (cmock_call_instance->Expected_out_raw == NULL)
      { UNITY_TEST_ASSERT_NULL(out_raw, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_out_raw, out_raw, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_adc_oneshot_read(CMOCK_adc_oneshot_read_CALL_INSTANCE* cmock_call_instance, adc_oneshot_unit_handle_t handle, adc_channel_t channel, int* out_raw);
void CMockExpectParameters_adc_oneshot_read(CMOCK_adc_oneshot_read_CALL_INSTANCE* cmock_call_instance, adc_oneshot_unit_handle_t handle, adc_channel_t channel, int* out_raw)
{
  memcpy((void*)(&cmock_call_instance->Expected_handle), (const void*)(&handle),
         sizeof(adc_oneshot_unit_handle_t[sizeof(handle) == sizeof(adc_oneshot_unit_handle_t) ? 1 : -1])); /* add adc_oneshot_unit_handle_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_channel), (const void*)(&channel),
         sizeof(adc_channel_t[sizeof(channel) == sizeof(adc_channel_t) ? 1 : -1])); /* add adc_channel_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_out_raw = out_raw;
}

void adc_oneshot_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_oneshot_unit_handle_t handle, adc_channel_t channel, int* out_raw, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_oneshot_read_CALL_INSTANCE));
  CMOCK_adc_oneshot_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_oneshot_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_oneshot_read_CallInstance = CMock_Guts_MemChain(Mock.adc_oneshot_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_adc_oneshot_read(cmock_call_instance, handle, channel, out_raw);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void adc_oneshot_del_unit(adc_oneshot_unit_handle_t handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_adc_oneshot_del_unit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_adc_oneshot_del_unit);
  cmock_call_instance = (CMOCK_adc_oneshot_del_unit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.adc_oneshot_del_unit_CallInstance);
  Mock.adc_oneshot_del_unit_CallInstance = CMock_Guts_MemNext(Mock.adc_oneshot_del_unit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_adc_oneshot_del_unit,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_handle, &handle, sizeof(adc_oneshot_unit_handle_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_adc_oneshot_del_unit(CMOCK_adc_oneshot_del_unit_CALL_INSTANCE* cmock_call_instance, adc_oneshot_unit_handle_t handle);
void CMockExpectParameters_adc_oneshot_del_unit(CMOCK_adc_oneshot_del_unit_CALL_INSTANCE* cmock_call_instance, adc_oneshot_unit_handle_t handle)
{
  memcpy((void*)(&cmock_call_instance->Expected_handle), (const void*)(&handle),
         sizeof(adc_oneshot_unit_handle_t[sizeof(handle) == sizeof(adc_oneshot_unit_handle_t) ? 1 : -1])); /* add adc_oneshot_unit_handle_t to :treat_as_array if this causes an error */
}

void adc_oneshot_del_unit_CMockExpect(UNITY_LINE_TYPE cmock_line, adc_oneshot_unit_handle_t handle)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_oneshot_del_unit_CALL_INSTANCE));
  CMOCK_adc_oneshot_del_unit_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_oneshot_del_unit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_oneshot_del_unit_CallInstance = CMock_Guts_MemChain(Mock.adc_oneshot_del_unit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_adc_oneshot_del_unit(cmock_call_instance, handle);
}

esp_err_t adc_cali_create_scheme_curve_fitting(const adc_cali_curve_fitting_config_t* config, adc_cali_handle_t* ret_handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_adc_cali_create_scheme_curve_fitting);
  cmock_call_instance = (CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.adc_cali_create_scheme_curve_fitting_CallInstance);
  Mock.adc_cali_create_scheme_curve_fitting_CallInstance = CMock_Guts_MemNext(Mock.adc_cali_create_scheme_curve_fitting_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_adc_cali_create_scheme_curve_fitting,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_config, config, sizeof(const adc_cali_curve_fitting_config_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_adc_cali_create_scheme_curve_fitting,CMockString_ret_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_ret_handle, ret_handle, sizeof(adc_cali_handle_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_adc_cali_create_scheme_curve_fitting(CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE* cmock_call_instance, const adc_cali_curve_fitting_config_t* config, adc_cali_handle_t* ret_handle);
void CMockExpectParameters_adc_cali_create_scheme_curve_fitting(CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE* cmock_call_instance, const adc_cali_curve_fitting_config_t* config, adc_cali_handle_t* ret_handle)
{
  cmock_call_instance->Expected_config = config;
  cmock_call_instance->Expected_ret_handle = ret_handle;
}

void adc_cali_create_scheme_curve_fitting_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const adc_cali_curve_fitting_config_t* config, adc_cali_handle_t* ret_handle, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE));
  CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_cali_create_scheme_curve_fitting_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_cali_create_scheme_curve_fitting_CallInstance = CMock_Guts_MemChain(Mock.adc_cali_create_scheme_curve_fitting_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_adc_cali_create_scheme_curve_fitting(cmock_call_instance, config, ret_handle);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

esp_err_t adc_cali_raw_to_voltage(adc_cali_handle_t handle, int adc_raw, int* voltage_mv)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_adc_cali_raw_to_voltage);
  cmock_call_instance = (CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.adc_cali_raw_to_voltage_CallInstance);
  Mock.adc_cali_raw_to_voltage_CallInstance = CMock_Guts_MemNext(Mock.adc_cali_raw_to_voltage_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_adc_cali_raw_to_voltage,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_handle, &handle, sizeof(adc_cali_handle_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_adc_cali_raw_to_voltage,CMockString_adc_raw);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_adc_raw, adc_raw, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_adc_cali_raw_to_voltage,CMockString_voltage_mv);
    if (cmock_call_instance->Expected_voltage_mv == NULL)
      { UNITY_TEST_ASSERT_NULL(voltage_mv, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_voltage_mv, voltage_mv, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_adc_cali_raw_to_voltage(CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE* cmock_call_instance, adc_cali_handle_t handle, int adc_raw, int* voltage_mv);
void CMockExpectParameters_adc_cali_raw_to_voltage(CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE* cmock_call_instance, adc_cali_handle_t handle, int adc_raw, int* voltage_mv)
{
  memcpy((void*)(&cmock_call_instance->Expected_handle), (const void*)(&handle),
         sizeof(adc_cali_handle_t[sizeof(handle) == sizeof(adc_cali_handle_t) ? 1 : -1])); /* add adc_cali_handle_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_adc_raw = adc_raw;
  cmock_call_instance->Expected_voltage_mv = voltage_mv;
}

void adc_cali_raw_to_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_cali_handle_t handle, int adc_raw, int* voltage_mv, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE));
  CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_cali_raw_to_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_cali_raw_to_voltage_CallInstance = CMock_Guts_MemChain(Mock.adc_cali_raw_to_voltage_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_adc_cali_raw_to_voltage(cmock_call_instance, handle, adc_raw, voltage_mv);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void adc_cali_delete_scheme_curve_fitting(adc_cali_handle_t handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_adc_cali_delete_scheme_curve_fitting);
  cmock_call_instance = (CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.adc_cali_delete_scheme_curve_fitting_CallInstance);
  Mock.adc_cali_delete_scheme_curve_fitting_CallInstance = CMock_Guts_MemNext(Mock.adc_cali_delete_scheme_curve_fitting_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_adc_cali_delete_scheme_curve_fitting,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_handle, &handle, sizeof(adc_cali_handle_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_adc_cali_delete_scheme_curve_fitting(CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE* cmock_call_instance, adc_cali_handle_t handle);
void CMockExpectParameters_adc_cali_delete_scheme_curve_fitting(CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE* cmock_call_instance, adc_cali_handle_t handle)
{
  memcpy((void*)(&cmock_call_instance->Expected_handle), (const void*)(&handle),
         sizeof(adc_cali_handle_t[sizeof(handle) == sizeof(adc_cali_handle_t) ? 1 : -1])); /* add adc_cali_handle_t to :treat_as_array if this causes an error */
}

void adc_cali_delete_scheme_curve_fitting_CMockExpect(UNITY_LINE_TYPE cmock_line, adc_cali_handle_t handle)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE));
  CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_cali_delete_scheme_curve_fitting_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_cali_delete_scheme_curve_fitting_CallInstance = CMock_Guts_MemChain(Mock.adc_cali_delete_scheme_curve_fitting_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_adc_cali_delete_scheme_curve_fitting(cmock_call_instance, handle);
}

const char* esp_err_to_name(esp_err_t code)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_err_to_name);
  cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_err_to_name_CallInstance);
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemNext(Mock.esp_err_to_name_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_esp_err_to_name,CMockString_code);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_code, &code, sizeof(esp_err_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_err_to_name(CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance, esp_err_t code);
void CMockExpectParameters_esp_err_to_name(CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance, esp_err_t code)
{
  memcpy((void*)(&cmock_call_instance->Expected_code), (const void*)(&code),
         sizeof(esp_err_t[sizeof(code) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_err_to_name_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t code, const char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_err_to_name_CALL_INSTANCE));
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemChain(Mock.esp_err_to_name_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_esp_err_to_name(cmock_call_instance, code);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

