/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKESP_ADC_MOCK_HEADERS_H
#define _MOCKESP_ADC_MOCK_HEADERS_H

#include "unity.h"
#include "esp_adc_mock_headers.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockesp_adc_mock_headers_Init(void);
void Mockesp_adc_mock_headers_Destroy(void);
void Mockesp_adc_mock_headers_Verify(void);




#define adc_oneshot_new_unit_Expect(init_config, ret_unit) TEST_FAIL_MESSAGE("adc_oneshot_new_unit requires _ExpectAndReturn");
#define adc_oneshot_new_unit_ExpectAndReturn(init_config, ret_unit, cmock_retval) adc_oneshot_new_unit_CMockExpectAndReturn(__LINE__, init_config, ret_unit, cmock_retval)
void adc_oneshot_new_unit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const adc_oneshot_unit_init_cfg_t* init_config, adc_oneshot_unit_handle_t* ret_unit, esp_err_t cmock_to_return);
#define adc_oneshot_config_channel_Expect(handle, channel, config) TEST_FAIL_MESSAGE("adc_oneshot_config_channel requires _ExpectAndReturn");
#define adc_oneshot_config_channel_ExpectAndReturn(handle, channel, config, cmock_retval) adc_oneshot_config_channel_CMockExpectAndReturn(__LINE__, handle, channel, config, cmock_retval)
void adc_oneshot_config_channel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_oneshot_unit_handle_t handle, adc_channel_t channel, const adc_oneshot_chan_cfg_t* config, esp_err_t cmock_to_return);
#define adc_oneshot_read_Expect(handle, channel, out_raw) TEST_FAIL_MESSAGE("adc_oneshot_read requires _ExpectAndReturn");
#define adc_oneshot_read_ExpectAndReturn(handle, channel, out_raw, cmock_retval) adc_oneshot_read_CMockExpectAndReturn(__LINE__, handle, channel, out_raw, cmock_retval)
void adc_oneshot_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_oneshot_unit_handle_t handle, adc_channel_t channel, int* out_raw, esp_err_t cmock_to_return);
#define adc_oneshot_del_unit_ExpectAndReturn(handle, cmock_retval) TEST_FAIL_MESSAGE("adc_oneshot_del_unit requires _Expect (not AndReturn)");
#define adc_oneshot_del_unit_Expect(handle) adc_oneshot_del_unit_CMockExpect(__LINE__, handle)
void adc_oneshot_del_unit_CMockExpect(UNITY_LINE_TYPE cmock_line, adc_oneshot_unit_handle_t handle);
#define adc_cali_create_scheme_curve_fitting_Expect(config, ret_handle) TEST_FAIL_MESSAGE("adc_cali_create_scheme_curve_fitting requires _ExpectAndReturn");
#define adc_cali_create_scheme_curve_fitting_ExpectAndReturn(config, ret_handle, cmock_retval) adc_cali_create_scheme_curve_fitting_CMockExpectAndReturn(__LINE__, config, ret_handle, cmock_retval)
void adc_cali_create_scheme_curve_fitting_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const adc_cali_curve_fitting_config_t* config, adc_cali_handle_t* ret_handle, esp_err_t cmock_to_return);
#define adc_cali_raw_to_voltage_Expect(handle, adc_raw, voltage_mv) TEST_FAIL_MESSAGE("adc_cali_raw_to_voltage requires _ExpectAndReturn");
#define adc_cali_raw_to_voltage_ExpectAndReturn(handle, adc_raw, voltage_mv, cmock_retval) adc_cali_raw_to_voltage_CMockExpectAndReturn(__LINE__, handle, adc_raw, voltage_mv, cmock_retval)
void adc_cali_raw_to_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_cali_handle_t handle, int adc_raw, int* voltage_mv, esp_err_t cmock_to_return);
#define adc_cali_delete_scheme_curve_fitting_ExpectAndReturn(handle, cmock_retval) TEST_FAIL_MESSAGE("adc_cali_delete_scheme_curve_fitting requires _Expect (not AndReturn)");
#define adc_cali_delete_scheme_curve_fitting_Expect(handle) adc_cali_delete_scheme_curve_fitting_CMockExpect(__LINE__, handle)
void adc_cali_delete_scheme_curve_fitting_CMockExpect(UNITY_LINE_TYPE cmock_line, adc_cali_handle_t handle);
#define esp_err_to_name_Expect(code) TEST_FAIL_MESSAGE("esp_err_to_name requires _ExpectAndReturn");
#define esp_err_to_name_ExpectAndReturn(code, cmock_retval) esp_err_to_name_CMockExpectAndReturn(__LINE__, code, cmock_retval)
void esp_err_to_name_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t code, const char* cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
