#ifndef VERSION_H
#define VERSION_H

#include <stdint.h>
#include <stdbool.h>

// Firmware version components (semantic versioning)
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 26

// Version string representation
#define FIRMWARE_VERSION_STRING "1.0.26"

// Build information (auto-generated by CMake)
#define GIT_COMMIT "unknown"
#define BUILD_DATE "unknown"

// Version structure for programmatic access
typedef struct
{
  uint8_t major;
  uint8_t minor;
  uint8_t patch;
} firmware_version_t;

// Version info structure with build metadata
typedef struct
{
  firmware_version_t version;
  const char *git_commit;
  const char *build_date;
  const char *target;
} firmware_info_t;

// Function declarations for version management
const char *get_firmware_version_string(void);
firmware_version_t get_firmware_version(void);
firmware_info_t get_firmware_info(void);
bool is_version_newer(const char *current_version, const char *remote_version);
int compare_versions(const char *version1, const char *version2);
firmware_version_t parse_version_string(const char *version_str);

#endif // VERSION_H
